paths:
  static: ''
  uploads: uploads
timezone: Asia/Singapore
markdown:
  engine: commonmark
  options: {}
collections_config:
  pages:
    path: /
    output: true
    url: /[slug].html
_editables:
  content:
    html: true
    text: true
    image: true
  elements:
    - p
    - h1
    - h2
    - h3
    - h4
    - h5
    - h6
    - img
    - main
    - div
    - section